name: newskproject
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.3
  lottie: ^1.1.0
  flutter_launcher_icons: ^0.10.0
  animated_splash_screen: ^1.3.0
  firebase_core: ^1.7.0
  firebase_database: ^8.0.0
  firebase_storage: ^10.2.10
  path_provider: ^2.0.9
  dio: ^4.0.6
  video_player: ^2.4.7
  cupertino_icons: ^1.0.2
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.2.7

  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true
  assets:
    - assets/customer.json
    - assets/loading.mp4
    - assets/s_logo.png
    - assets/s_logo_bg.png
    - assets/s_logo_item.png
    - assets/a.png
    - assets/b.png


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/s_logo_bg.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/s_logo_bg.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/s_logo_bg.png"
    icon_size: 48 # min:48, max:256, default: 48
    

flutter_native_splash:
  color: "#0B0C28"
  # background_image: "assets/bg.png"
  # image: "assets/s_logo.png"